### ISSUE TITLE
Can conversion wave and teleseismic wave arrival time be calculated?

### ISSUE THREAD

**Issue by gongchang96** [malcolmw/pykonal#10]
Can conversion wave and teleseismic wave arrival time be calculated?
thx

**Comment by malcolmw** [comment]
Hi, @gongchang96,

Yes, traveltimes can be computer for both converted and teleseismic waves, although this does take a little extra work for the user. The details on the best way to do this depend on the particular application.

What are you trying to do?

Thanks,
Malcolm

**Comment by gongchang96** [comment]
hi, 
    I want to computer the delay time for receiver functions in a local 3D model. how should I do?

   thanks
   chang

**Comment by malcolmw** [comment]
Hi, @gongchang96,

Take a look at the attached notebook. It demonstrates how to compute delay times in a local 3D model for waves converted by a horizontal interface at 40 km depth.

Let me know if that helps you achieve your goal.

- Malcolm

[moho_conversion.zip](https://github.com/malcolmw/pykonal/files/5278906/moho_conversion.zip)

**Comment by gongchang96** [comment]
Thanks for providing me notebook. It make me clearly understand how to compute using pykonal.

And if I would compute the travel time for Ppds or Ppss, can you give me some suggestions？

**Comment by malcolmw** [comment]
@gongchang96 I am unfamiliar with these phases, can you explain them to me so I can help you?

\- Malcolm

**Comment by gongchang96** [comment]
Maybe I didn't make it clear. I mean the Ppds or Ppss is the phases in receiver function. It is the teleseismic wave reflected downward by the free surface of the Earth as a P-wave or S-wave, and then reflected upward by the discontinuity as an S-wave. Because FMM is hard to compute the travel time for the reflected wave. So if you have any suggestions about it?

**Comment by malcolmw** [comment]
@gongchang96 OK, take a look at the attached notebook. It demonstrates how to trace rays and compute delay times for multiply reflected/converted phases in a 2D cartesian model. 

Let me know how it goes,
Malcolm

[moho_conversion.zip](https://github.com/malcolmw/pykonal/files/5295286/moho_conversion.zip)

**Comment by malcolmw** [comment]
Any success with the above notebook, @gongchang96?

**Comment by gongchang96** [comment]
@malcolmw Sorry, I just came back from a trip, I will test it with actual data in these two days.

**Comment by malcolmw** [comment]
@gongchang96, no problem. 

Let me know how it goes,
Malcolm

**Comment by malcolmw** [comment]
Closing this as inactive. Please feel free to reopen if you come back to this, @gongchang96.
