### ISSUE TITLE
source coordinate out of the nodes

### ISSUE THREAD

**Issue by saeedsltm** [malcolmw/pykonal#11]
Could be very helpful if we can put the source coordinate in any arbitrary x,y,z and not just instead a node. Especially if we're considering large distance between two adjacent nodes (dx,dy,dz), this functionality would be more important.

**Comment by malcolmw** [comment]
Hi, @saeedsltm,

I agree, and I wrote the PointSourceSolver class to do exactly that. Check out the [example here](https://malcolmw.github.io/pykonal-docs/examples/point_source_solver.html). 

Let me know if you have any trouble using that class.

\- Malcolm
