### ISSUE TITLE
Error installing pykonal on Windows

### ISSUE THREAD

**Issue by ecastillot** [malcolmw/pykonal#16]
Good morning

I am trying to install pykonal on Windows server, however, I have the next errors  . Can you help me?

![image](https://user-images.githubusercontent.com/63883182/130011257-12c28eac-ab08-49af-a2e9-a65e8e60c8c6.png)

Thanks a lot!

**Comment by malcolmw** [comment]
Hi, @ecastillot,

There are some known issues with PyKonal on Windows, and, unfortunately, I don't have the resources support Windows. In the future, I hope to be able to, but, until then, I suggest trying to run on Linux or Mac OS X if possible. Sorry for the bad news.

\- Malcolm
