### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by lukaszmoroz** [malcolmw/pykonal#18]
Hey, could you put the package on PyPI as well? Not everyone can use Conda, and I believe that nowadays PyPI supports publishing cython binary wheels.

**Comment by malcolmw** [comment]
Hi, @lukaszmoroz, Sure I can add to PyPI, but you don't need `conda` to install `pykonal`. Just clone the respository and run `pip install .` from the top level directory.

**Comment by lukaszmoroz** [comment]
I know that, but still, I think putting it on PyPI would help with discoverability (I was trying to use `scikit-fmm` initially with little success and only later, after a few more google searches I came across this repo).

Also, I'm using Poetry to manage my dependencies and installing your package from a git repo (or alternatively a local folder):
```toml
[tool.poetry.dependencies]
# ...
pykonal = { git = "https://github.com/malcolmw/pykonal.git", tag = "0.3.2b1" }
```
I experienced an issue: your `setup.py` imports `cython` and `numpy` but you don't specify them as build dependencies (in addition to install dependencies), so the package can't be built if you don't happen to have them already installed. Therefore you need a [`pyproject.toml`](https://github.com/lukaszmoroz/pykonal/blob/0.3.2b4/pyproject.toml) that specifies those (I can make a PR with it if you want).

With this change I'm able to install your package directly from github, but it's not the most convenient way (e.g. it doesn't allow specifying version ranges).

**Comment by malcolmw** [comment]
I see.  I haven't seen a workflow like yours before, so a PR would be great! Thanks for the feedback!

\-Malcolm

**Comment by malcolmw** [comment]
Closing this as complete (finally). Thanks @jobh!
