### ISSUE TITLE
Receive error on import on Mac M1 

### ISSUE THREAD

**Issue by beridel** [malcolmw/pykonal#24]
ImportError: dlopen(/Users/wbfrank/Projects/code/pykonal/pykonal/solver.cpython-310-darwin.so, 0x0002): tried: '/Users/wbfrank/Projects/code/pykonal/pykonal/solver.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by ngroebner** [comment]
I ran into the same issue. Not sure why, but seems like python was building an amd64 library instead of an arm64 library. Solved it by installing the package like this:

```arch -amd64 pip install .```

**Comment by malcolmw** [comment]
@beridel: Does the above solution work for you? You may need to switch the `-amd64` flag to `-x86_64`.
