### ISSUE TITLE
ERROR: Failed building wheel for pykonal

### ISSUE THREAD

**Issue by srinty** [malcolmw/pykonal#29]
Hi, I was trying to install pykonal in my mac. I am getting this error of failed to build wheel. I have installed wheel and setuptools using pip command. Also upgraded pip, wheel and setuptools. But still getting the same error. I am attaching a screenshot of my problem here. 
Can you please let me know how to fix this issue?

<img width="1256" alt="Screenshot 2023-01-30 at 11 46 53 AM" src="https://user-images.githubusercontent.com/90080501/215554052-ce4e02b3-cb38-4993-811d-bd73b17117b3.png">

**Comment by malcolmw** [comment]
Hi @srinty, Are you installing from source code or from PyPI? Installation via the PyPI does not currently work, so you should clone the repository and execute `pip install .` from the top-level directory.

**Comment by srinty** [comment]
Hi,

I am installing from source code, following these codes:

sh$> conda create --name pykonal -c conda-forge python=3.8 'cython>=0.29.14' h5py numpy scipy
sh$> conda activate pykonal
(pykonal)sh$> cd path/to/pykonal
(pykonal)sh$> pip install .

Regards,
Sadia

Sadia Marium Rinty
PhD Student | Earth Sciences
Class of 2025
Center for Earthquake Research and Information
The University of Memphis
3890 Central Ave. | Memphis TN 38152
901.678.2007
________________________________

**Comment by malcolmw** [comment]
OK, try removing the `pyproject.toml` and `MANIFEST.in` files and trying again.

**Comment by srinty** [comment]
I couldn't find any MANIFEST.in file in the master folder. I removed the pyproject.toml file, but getting error again. I am attaching a snap of the error here for your reference.



Sadia Marium Rinty
PhD Student | Earth Sciences
Class of 2025
Center for Earthquake Research and Information
The University of Memphis
3890 Central Ave. | Memphis TN 38152
901.678.2007
________________________________

**Comment by srinty** [comment]
<img width="1215" alt="Screenshot 2023-01-30 at 12 58 13 PM" src="https://user-images.githubusercontent.com/90080501/215569579-42c0c671-c7b7-4d20-9562-8f40de1a8659.png">

**Comment by malcolmw** [comment]
OK, this looks like an environment issue: I think you are missing the `xcrun` executable. See the second to last line above [end of output] in the figure above.

**Comment by srinty** [comment]
Thank you so much. I fixed the problem. I had to install the command line tools for Xcode.

**Comment by malcolmw** [comment]
Great. Closing this issue as resolved.
