### ISSUE TITLE
Discussion: implementing traveltime tomography on circular geometry.

### ISSUE THREAD

**Issue by makeabhishek** [malcolmw/pykonal#34]
Hi,
I want to implement travel time tomography for body waves. 
I saw that ttcrpy used pykonal for travel time tomography. 

Is it possible to use ttcrpy/pykonal to implement travel time tomography for circular geometry?

**Comment by malcolmw** [comment]
Hi @makeabhishek, Yes it is certainly possible to use PyKonal for traveltime tomography with circular geometry. I took a quick look at the ttcrpy project but do not see any references to PyKonal there. Can you provide a little more detail on what you want to do, and what relevant work has been done within the ttcrpy framework?

Thanks,
Malcolm

**Comment by malcolmw** [comment]
I added a [tutorial notebook](https://github.com/malcolmw/pykonal/tree/master/tutorials/tomography) that demonstrates the tomography method of [Fang et al. (2020)](https://pubs.geoscienceworld.org/ssa/srl/article/91/1/343/574663/Parsimonious-Seismic-Tomography-with-Poisson) in 2-D Cartesian coordinates.

Take a look at that notebook and see if you can adapt it to your needs. Let me know if you get stuck.

Cheers,
Malcolm

**Comment by malcolmw** [comment]
Thanks @makeabhishek. This is definitely possible with PyKonal. Let me know if you get stuck.

Cheers,
Malcolm
