### ISSUE TITLE
Can't import pykonal. Though installation went well.

### ISSUE THREAD

**Issue by himansh78** [malcolmw/pykonal#35]
Hi , I installed pykonal which went well. As I am trying to import it, it is showing following error

`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b47641216184> in <module>
      1 import skfmm
      2 dir='out_create_piggyback2d/'
----> 3 import pykonal

~\Anaconda3\lib\site-packages\pykonal\__init__.py in <module>
      8 )
      9 
---> 10 from .solver import EikonalSolver
     11 
     12 from . import constants

pykonal\solver.pyx in init pykonal.solver()

pykonal\fields.pyx in init pykonal.fields()

~\Anaconda3\lib\site-packages\h5py\__init__.py in <module>
     44 _errors.silence_errors()
     45 
---> 46 from ._conv import register_converters as _register_converters
     47 _register_converters()
     48 

h5py\h5t.pxd in init h5py._conv()

h5py\h5t.pyx in init h5py.h5t()

~\Anaconda3\lib\site-packages\numpy\__init__.py in __getattr__(attr)
    318             return Tester
    319 
--> 320         raise AttributeError("module {!r} has no attribute "
    321                              "{!r}".format(__name__, attr))
    322 

AttributeError: module 'numpy' has no attribute 'typeDict'
`

my numpy version is 1.24.2 and scipy is 1.5.2
I tried with downgraded versions as well.
Please help

**Comment by malcolmw** [comment]
Hi @himansh78, It looks like there is some version skew here. Are you using `virtualenv` or `conda`? Can you try reinstalling `pykonal` and its dependencies in a fresh environment?

**Comment by malcolmw** [comment]
Closing this as stale.
