### ISSUE TITLE
Mismatch release <-> version

### ISSUE THREAD

**Issue by jobh** [malcolmw/pykonal#37]
Hi,

The release is tagged as 0.2.3b4, but `__version__` is 0.3.2b4. See for example

https://github.com/malcolmw/pykonal/blob/0.2.3b4/pykonal/__version__.py
```
__major_version__  = 0
__minor_version__  = 3
__patch__          = 2
__release__        = "b4"
```

**Comment by jobh** [comment]
Also, the latest version on pypi is 0.3.2b6: https://pypi.org/project/pykonal/#history

...which would appear to be newer than the current master (b5 - see https://github.com/malcolmw/pykonal/blob/master/pykonal/__version__.py)

I'm a bit confused ;-)

**Comment by malcolmw** [comment]
Good catch! Thanks @jobh. The PyPI version unfortunately does not work. I have had trouble setting up the necessary configuration to install the cython code, so please ignore `0.3.2b6`. I will delete it from the index and resolve the mismatch between the source code and the release tag.

**Comment by malcolmw** [comment]
Closing this as fixed. Thanks again!

**Comment by jobh** [comment]
Thanks @malcolmw! If I may suggest something, it is to jump to 0.4.0 (or even 1.0.0 :open_mouth:) in the near future, to supersede any existing versions existing "out there".

With regards to the pypi package, it would be nice to have. Is there anything with regards to that that I (or others) may assist with?
