### ISSUE TITLE
Error in pykonal.solver.EikonalSolver(coord_sys="cartesian").trial.push(*idx)

### ISSUE THREAD

**Issue by hatsyim** [malcolmw/pykonal#7]
I tried the notebooks provided under this [`link`](https://malcolmw.github.io/pykonal-docs/white_et_al_figures.html#download). I am running on `Windows 10` with `Python 3.7.7` and [`Pykonal 0.3.2b1`](https://github.com/malcolmw/pykonal/releases) package.

> ValueError Traceback (most recent call last)
<ipython-input-8-acfc2fc30288> in <module>
     15 solver.unknown[src_idx] = False
     16 # Add source node to *Trial*.
---> 17 solver.trial.push(*src_idx)
     18 # Solve the system.
     19 solver.solve()
pykonal\solver.pyx in pykonal.solver.EikonalSolver.trial.__get__()
pykonal\heapq.pyx in pykonal.heapq.Heap.__init__()
ValueError: Buffer dtype mismatch, expected 'Py_ssize_t' but got 'long'

**Comment by malcolmw** [comment]
@hatsyim Thanks for reporting this bug.

This is a Windows-specific bug that has to do with the internal representations of the _int_ data type in Python and _Py\_ssize\_t_ data type in the C API. The type casting is handled automatically on Linux and OSX but fails on Windows. I am looking into the proper solution to this problem.

Thanks again for reporting.

**Comment by malcolmw** [comment]
This is a peculiar bug, the fix for which on Windows—at least the one that I tried—breaks the code on Linux.  Fixing this is low priority until this is a larger base of users on Windows, so I am closing this as _not going to fix_ until then.
